export const FETCH_UPCOMING_EVENT = 'FETCH_UPCOMING_EVENT';
export const FETCH_UPCOMING_EVENT_SUCCESS = 'FETCH_UPCOMING_EVENT_SUCCESS';
export const FETCH_UPCOMING_EVENT_FAIL = 'FETCH_UPCOMING_EVENT_FAIL';