export const FETCH_UPCOMING_EVENT = 'FETCH_UPCOMING_EVENT';
export const FETCH_UPCOMING_EVENT_SUCCESS = 'FETCH_UPCOMING_EVENT_SUCCESS';
export const FETCH_UPCOMING_EVENT_FAIL = 'FETCH_UPCOMING_EVENT_FAIL';
export const FETCH_FEEDS = 'FETCH_FEEDS';
export const FETCH_FEEDS_SUCCESS = 'FETCH_FEEDS_SUCCESS';
export const FETCH_FEEDS_FAIL = 'FETCH_FEEDS_FAIL';